namespace: sabre1041

name: openshift_equinix

version: 0.0.3

readme: README.md

authors:
  - Andrew Block <ablock@redhat.com>
  - Federico Rossi <ferossi@redhat.com>

description: ""

license_file: LICENSE

tags:
  - cloud
  - equinix
  - openshift
  - metal

dependencies:
  "equinix.cloud": ">=0.0.1"
  "containers.podman": ">=1.10.1"

repository: https://github.com/sabre1041/openshift_equinix

documentation: https://github.com/sabre1041/openshift_equinix

homepage: https://github.com/sabre1041/openshift_equinix

issues: https://github.com/sabre1041/openshift_equinix/issues

build_ignore:
  - requirements.txt
  - .gitignore
