---

- name: Generate ABI ISO Image
  ansible.builtin.command: "openshift-install --dir {{ content_dir }} agent create image"

- name: Move ABI ISO Image to Data Directory
  ansible.builtin.command: "mv {{ content_dir }}/agent.x86_64.iso {{ data_dir }}/image.iso"

- name: Create iPXE artifacts from the ISO
  containers.podman.podman_container:
    name: "{{ openshift_cluster_name }}-ipxe"
    image: "{{ ipxe_image }}"
    detach: false
    state: started
    remove: true
    volume:
      - "{{ data_dir }}:/data:Z"

- name: Create nginx container
  containers.podman.podman_container:
    name: nginx
    image: "{{ nginx_image }}"
    detach: true
    state: started
    remove: true
    recreate: true
    ports:
      - 8888:8080
    volume:
      - "{{ data_dir }}/ipxe:/app:ro"

- name: Update ipxe configuration file
  ansible.builtin.replace:
    regexp: localhost
    replace: "{{ utility_server_ip }}"
    path: "{{ data_dir }}/ipxe/ipxe"

- name: Update OpenShift Node
  equinix.cloud.metal_device:
    project_id: "{{ equinix_project_id }}"
    id: "{{ openshift_node_id }}"
    metal_api_token: "{{ equinix_api_token }}"
    ipxe_script_url: "{{ utility_server_ipxe_url }}"
    userdata: ""
    always_pxe: true
  delegate_to: localhost

- name: Restart Node
  ansible.builtin.uri:
    url: "https://api.equinix.com/metal/v1/devices/{{ openshift_node_id }}/actions"
    method: POST
    body_format: json
    status_code: [200, 202]
    headers:
      X-Auth-Token: "{{ equinix_api_token }}"
      Content-Type: "application/json"
    body:
      type: reboot
  delegate_to: localhost

- name: (OCP) Monitor installation status
  ansible.builtin.shell: openshift-install --dir {{ content_dir }} agent wait-for bootstrap-complete --log-level=debug 2> {{ temp_dir }}/install.log &
  async: 1800
  poll: 30

- name: (OCP) Monitor installation status - cluster installation start
  ansible.builtin.wait_for:
    path: "{{ temp_dir }}/install.log"
    search_regex: Cluster installation in progress
    connect_timeout: 1200
    timeout: 1200

- name: Update OpenShift Node (Disable IPXE)
  equinix.cloud.metal_device:
    project_id: "{{ equinix_project_id }}"
    id: "{{ openshift_node_id }}"
    metal_api_token: "{{ equinix_api_token }}"
    always_pxe: false
  delegate_to: localhost

- name: Stop nginx container
  containers.podman.podman_container:
    name: nginx
    state: stopped

- name: Monitor installation status - bootstrap-completed
  ansible.builtin.command: "openshift-install --dir {{ content_dir }} agent wait-for bootstrap-complete --log-level=debug"
  timeout: 2500
  register: abi_bootstrap

- name: Monitor installation status - install-completed
  ansible.builtin.command: openshift-install --dir {{ content_dir }} agent wait-for install-complete --log-level=debug
  register: abi_install
  timeout: 2500

- name: Read Content of kubeadmin-password file
  ansible.builtin.slurp:
    path: "{{ content_dir }}/auth/kubeadmin-password"
  register: kubeadmin_password

- name: Print summary
  ansible.builtin.debug:
    msg:
      - "================ SUMMARY ================="
      - "OpenShift console: https://openshift-console-openshift.apps.{{ openshift_cluster_name }}.{{ openshift_base_domain }}"
      - "Kubeadmin password: {{ kubeadmin_password['content'] | b64decode }}"
